version: "3.0"

services:
  todo_dart_app:
    container_name: todo_dart_app
    build: .
    volumes:
      - './lib:/www/dartapp/lib'
      - './bin:/www/dartapp/bin'
      - './test:/www/dartapp/test'
    ports:
      - 9090:8000